# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Demo.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QLabel,
    QPushButton, QSizePolicy, QTextEdit, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1201, 852)
        self.startVideo = QPushButton(Form)
        self.startVideo.setObjectName(u"startVideo")
        self.startVideo.setGeometry(QRect(990, 129, 180, 61))
        self.stopVideo = QPushButton(Form)
        self.stopVideo.setObjectName(u"stopVideo")
        self.stopVideo.setGeometry(QRect(990, 220, 180, 61))
        self.exit_btn = QPushButton(Form)
        self.exit_btn.setObjectName(u"exit_btn")
        self.exit_btn.setGeometry(QRect(990, 310, 180, 61))
        self.label_2 = QLabel(Form)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(1000, 60, 67, 17))
        self.Id = QTextEdit(Form)
        self.Id.setObjectName(u"Id")
        self.Id.setGeometry(QRect(1050, 50, 104, 30))
        self.line_2 = QFrame(Form)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(0, 410, 1641, 20))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_3 = QFrame(Form)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(1320, 0, 20, 511))
        self.line_3.setFrameShape(QFrame.VLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.label_20 = QLabel(Form)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(120, 0, 301, 81))
        font = QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.label_20.setFont(font)
        self.armangle = QLabel(Form)
        self.armangle.setObjectName(u"armangle")
        self.armangle.setGeometry(QRect(650, 20, 191, 71))
        self.armangle.setFont(font)
        self.label_15 = QLabel(Form)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(50, 440, 441, 61))
        self.label_15.setFont(font)
        self.label_15.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.line_4 = QFrame(Form)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(940, 0, 20, 421))
        self.line_4.setFrameShape(QFrame.VLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.img_label_2 = QLabel(Form)
        self.img_label_2.setObjectName(u"img_label_2")
        self.img_label_2.setGeometry(QRect(20, 510, 501, 311))
        self.img_label_2.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(Form)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QRect(580, 150, 79, 61))
        font1 = QFont()
        font1.setFamilies([u"Ubuntu Condensed"])
        font1.setPointSize(24)
        font1.setBold(True)
        self.label_4.setFont(font1)
        self.left_hand = QLabel(Form)
        self.left_hand.setObjectName(u"left_hand")
        self.left_hand.setGeometry(QRect(650, 140, 311, 81))
        self.left_hand.setFont(font1)
        self.label_3 = QLabel(Form)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(580, 280, 79, 51))
        self.label_3.setFont(font1)
        self.right_hand = QLabel(Form)
        self.right_hand.setObjectName(u"right_hand")
        self.right_hand.setGeometry(QRect(650, 270, 311, 81))
        self.right_hand.setFont(font1)
        self.layoutWidget = QWidget(Form)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(580, 680, 271, 71))
        self.horizontalLayout_6 = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.label_10 = QLabel(self.layoutWidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setMaximumSize(QSize(126, 16777215))
        self.label_10.setFont(font)

        self.horizontalLayout_6.addWidget(self.label_10)

        self.depthPostureLabel = QLabel(self.layoutWidget)
        self.depthPostureLabel.setObjectName(u"depthPostureLabel")
        self.depthPostureLabel.setFont(font)

        self.horizontalLayout_6.addWidget(self.depthPostureLabel)

        self.layoutWidget1 = QWidget(Form)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(580, 750, 271, 71))
        self.horizontalLayout_7 = QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.label_11 = QLabel(self.layoutWidget1)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setFont(font)

        self.horizontalLayout_7.addWidget(self.label_11)

        self.label_18 = QLabel(self.layoutWidget1)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setFont(font)

        self.horizontalLayout_7.addWidget(self.label_18)

        self.layoutWidget2 = QWidget(Form)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.layoutWidget2.setGeometry(QRect(880, 680, 271, 71))
        self.horizontalLayout_8 = QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.label_12 = QLabel(self.layoutWidget2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setFont(font)

        self.horizontalLayout_8.addWidget(self.label_12)

        self.postureLabel = QLabel(self.layoutWidget2)
        self.postureLabel.setObjectName(u"postureLabel")
        self.postureLabel.setFont(font)

        self.horizontalLayout_8.addWidget(self.postureLabel)

        self.layoutWidget3 = QWidget(Form)
        self.layoutWidget3.setObjectName(u"layoutWidget3")
        self.layoutWidget3.setGeometry(QRect(880, 750, 271, 71))
        self.horizontalLayout_9 = QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.label_13 = QLabel(self.layoutWidget3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setFont(font)

        self.horizontalLayout_9.addWidget(self.label_13)

        self.label_17 = QLabel(self.layoutWidget3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setFont(font)

        self.horizontalLayout_9.addWidget(self.label_17)

        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(580, 530, 71, 69))
        self.label.setFont(font)
        self.depthLabel = QLabel(Form)
        self.depthLabel.setObjectName(u"depthLabel")
        self.depthLabel.setGeometry(QRect(660, 530, 191, 69))
        self.depthLabel.setFont(font)
        self.label_5 = QLabel(Form)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(890, 538, 71, 51))
        self.label_5.setFont(font)
        self.frequencyLabel = QLabel(Form)
        self.frequencyLabel.setObjectName(u"frequencyLabel")
        self.frequencyLabel.setGeometry(QRect(970, 530, 191, 69))
        font2 = QFont()
        font2.setPointSize(12)
        font2.setBold(True)
        self.frequencyLabel.setFont(font2)
        self.img_label_1 = QLabel(Form)
        self.img_label_1.setObjectName(u"img_label_1")
        self.img_label_1.setGeometry(QRect(10, 70, 501, 311))
        self.img_label_1.setAlignment(Qt.AlignCenter)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"AI CPR ", None))
        self.startVideo.setText(QCoreApplication.translate("Form", u"\u958b\u59cb\u5075\u6e2c", None))
        self.stopVideo.setText(QCoreApplication.translate("Form", u"\u7d50\u675f\u5075\u6e2c", None))
        self.exit_btn.setText(QCoreApplication.translate("Form", u"\u96e2\u958b", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"\u7de8\u865f", None))
        self.label_20.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">CPR Screen</span></p></body></html>", None))
        self.armangle.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\">\u624b\u81c2\u89d2\u5ea6 </p></body></html>", None))
        self.label_15.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">Compression Position</span></p></body></html>", None))
        self.img_label_2.setText(QCoreApplication.translate("Form", u"img_label_2", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"\u5de6\u624b", None))
        self.left_hand.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:400;\">\u5c1a\u672a\u958b\u59cb\u5075\u6e2c</span></p></body></html>", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"\u53f3\u624b", None))
        self.right_hand.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:400;\">\u5c1a\u672a\u958b\u59cb\u5075\u6e2c</span></p></body></html>", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:18pt;\">Depth</span></p></body></html>", None))
        self.depthPostureLabel.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#000000;\">Normal</span></p></body></html>", None))
        self.label_11.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:18pt;\">Rate</span></p></body></html>", None))
        self.label_18.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#000000;\">Normal</span></p></body></html>", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:18pt;\">Posture</span></p></body></html>", None))
        self.postureLabel.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#000000;\">Normal</span></p></body></html>", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:18pt;\">Position</span></p></body></html>", None))
        self.label_17.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#000000;\">Normal</span></p></body></html>", None))
        self.label.setText(QCoreApplication.translate("Form", u"\u6df1\u5ea6", None))
        self.depthLabel.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:400;\">\u5c1a\u672a\u958b\u59cb\u5075\u6e2c</span></p></body></html>", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"\u983b\u7387", None))
        self.frequencyLabel.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:400;\">\u5c1a\u672a\u958b\u59cb\u5075\u6e2c</span></p></body></html>", None))
        self.img_label_1.setText(QCoreApplication.translate("Form", u"img_label_1", None))
    # retranslateUi

